#!/bin/bash
# Train MGHD on the gross BB code with Stim noise and LSD teacher
# Usage: bash scripts/run_bb_gross_heron.sh

set -e
cd "$(dirname "$0")/.."

# Auto-launch in tmux if not already inside one.
# We fix the family to "gross" for this run.
SESSION_NAME="bb_gross"
if [ -z "$TMUX" ]; then
    if tmux has-session -t $SESSION_NAME 2>/dev/null; then
        echo "Session $SESSION_NAME exists. Attaching..."
        tmux attach -t $SESSION_NAME
        exit 0
    fi
    tmux new-session -d -s $SESSION_NAME
    tmux send-keys -t $SESSION_NAME "cd $(pwd) && bash scripts/run_bb_gross_heron.sh inside_tmux" C-m
    echo "Started training in tmux session: $SESSION_NAME"
    echo "Attach with: tmux attach -t $SESSION_NAME"
    exit 0
fi

# Inside tmux
source /u/home/kulp/miniconda3/etc/profile.d/conda.sh
conda activate mlqec-env

# Configuration (single-GPU, gross code, Stim + LSD teacher, OFFLINE crops)
export CUDA_VISIBLE_DEVICES=1

# Path to circuit-level gross crops generated by mghd/tools/gross_circuit_dataset.py
CROPS_DIR="${CROPS_DIR:-/u/home/kulp/MGHD/data/gross_circuit_crops}"

SAVE_DIR="/u/home/kulp/mghd_runs/gross_lsd_stim"
mkdir -p "$SAVE_DIR"

echo "Training gross code (offline, circuit-level DEM) with Stim sampler and LSD=1.0 teacher"
echo "Crops dir: $CROPS_DIR"
echo "Save dir : $SAVE_DIR"

python -m mghd.cli.train \
    --data-root "$CROPS_DIR" \
    --family gross \
    --distance 12 \
    --sampler stim \
    --teacher-mix lsd=1.0 \
    --epochs 240 \
    --p-curriculum 0.0005,0.0010,0.0015,0.0020,0.0025,0.0030 \
    --epochs-per-p 40 \
    --shots-per-epoch 80000 \
    --workers 8 \
    --prefetch-factor 2 \
    --batch 48 \
    --amp bf16 \
    --context-source none \
    --progress-prints 50 \
    --save "$SAVE_DIR"

echo "Training finished"
